from __future__ import annotations

from typing import Any, Dict

from api.utils.analyze_recovery_cache import PIPELINE_VERSION

from .contracts import ParseFilePipelineArtifacts


def build_parse_file_response_payload_from_artifacts(artifacts: ParseFilePipelineArtifacts) -> Dict[str, Any]:
    result = artifacts.result
    canonical_skills_count_deduped = sum(
        1 for m in artifacts.canonical_mapping.canonical_skills_list if m.get("canonical_id")
    )

    return dict(
        source=result["source"],
        mode=artifacts.mode,
        pipeline_used="canonical_compass",
        pipeline_variant=artifacts.pipeline_variant,
        compass_e_enabled=artifacts.compass_e_enabled,
        domain_skills_active=artifacts.domain_skills_active,
        domain_skills_pending_count=artifacts.domain_skills_pending_count,
        llm_fired=artifacts.llm_fired,
        ai_available=artifacts.ai_available,
        ai_added_count=artifacts.ai_added_count,
        ai_error=artifacts.ai_error,
        filename=artifacts.filename,
        content_type=artifacts.content_type,
        extracted_text_length=len(artifacts.cv_text),
        extracted_text_hash=artifacts.extracted_text_hash,
        profile_fingerprint=artifacts.profile_fingerprint,
        recovery_pipeline_version=PIPELINE_VERSION,
        canonical_count=result["canonical_count"],
        raw_detected=result["raw_detected"],
        validated_skills=result["validated_skills"],
        filtered_out=result["filtered_out"],
        validated_items=result.get("validated_items", []),
        validated_labels=result.get("validated_labels", []),
        raw_tokens=result.get("raw_tokens", []),
        filtered_tokens=result.get("filtered_tokens", []),
        alias_hits_count=result.get("alias_hits_count", 0),
        alias_hits=result.get("alias_hits", []),
        skill_groups=result.get("skill_groups", []),
        skills_uri_count=result.get("skills_uri_count", 0),
        skills_uri_collapsed_dupes=result.get("skills_uri_collapsed_dupes", 0),
        skills_unmapped_count=result.get("skills_unmapped_count", 0),
        skills_dupes=result.get("skills_dupes", []),
        skills_raw=result["skills_raw"],
        skills_canonical=result["skills_canonical"],
        profile=artifacts.enrichment.profile,
        warnings=result.get("warnings", []) + artifacts.warnings + artifacts.pipeline_warnings,
        profile_cluster=artifacts.profile_cluster,
        resolved_to_esco=artifacts.enrichment.resolved_to_esco,
        skill_provenance=artifacts.enrichment.skill_provenance,
        baseline_esco_count=artifacts.enrichment.baseline_esco_count,
        injected_esco_from_domain=artifacts.enrichment.injected_esco_from_domain,
        total_esco_count=artifacts.enrichment.total_esco_count,
        matching_input_trace=artifacts.matching_input.matching_input_trace,
        rejected_tokens=artifacts.enrichment.rejected_tokens_list,
        tight_candidates=artifacts.skill_candidates.tight_candidates,
        tight_metrics=artifacts.skill_candidates.tight_metrics,
        mapping_inputs_count=len(artifacts.canonical_mapping.mapping_inputs or []),
        structured_signal_units=artifacts.structured_extraction.structured_units,
        top_signal_units=artifacts.structured_extraction.top_signal_units,
        secondary_signal_units=artifacts.structured_extraction.secondary_signal_units,
        structured_signal_stats=artifacts.structured_extraction.stats,
        generic_filter_removed=artifacts.structured_extraction.generic_filter_removed,
        enriched_signals=artifacts.enriched_signals.enriched_signals,
        concept_signals=artifacts.concept_signals.concept_signals,
        canonical_skills=artifacts.canonical_mapping.canonical_skills_list,
        canonical_skills_count=canonical_skills_count_deduped,
        canonical_hierarchy_added=artifacts.canonical_mapping.canonical_hierarchy_added,
        preserved_explicit_skills=artifacts.canonical_mapping.preserved_explicit_skills,
        profile_summary_skills=artifacts.canonical_mapping.profile_summary_skills,
        dropped_by_priority=artifacts.canonical_mapping.dropped_by_priority,
        priority_trace=artifacts.canonical_mapping.priority_trace,
        priority_stats=artifacts.canonical_mapping.priority_stats,
        skill_proximity_links=artifacts.canonical_mapping.skill_proximity_links,
        skill_proximity_count=artifacts.canonical_mapping.skill_proximity_count,
        skill_proximity_summary=artifacts.canonical_mapping.skill_proximity_summary,
        profile_intelligence=artifacts.profile_intelligence.data,
        profile_intelligence_ai_assist=artifacts.profile_intelligence_ai_assist.data,
    )


def build_parse_baseline_response_payload_from_artifacts(
    artifacts: ParseFilePipelineArtifacts,
) -> Dict[str, Any]:
    result = artifacts.result
    return {
        "source": result["source"],
        "skills_raw": result["skills_raw"],
        "skills_canonical": result["skills_canonical"],
        "canonical_count": result["canonical_count"],
        "raw_detected": result["raw_detected"],
        "validated_skills": result["validated_skills"],
        "filtered_out": result["filtered_out"],
        "validated_items": result.get("validated_items", []),
        "validated_labels": result.get("validated_labels", []),
        "raw_tokens": result.get("raw_tokens", []),
        "filtered_tokens": result.get("filtered_tokens", []),
        "alias_hits_count": result.get("alias_hits_count", 0),
        "alias_hits": result.get("alias_hits", []),
        "skill_groups": result.get("skill_groups", []),
        "skills_uri_count": result.get("skills_uri_count", 0),
        "skills_uri_collapsed_dupes": result.get("skills_uri_collapsed_dupes", 0),
        "skills_unmapped_count": result.get("skills_unmapped_count", 0),
        "skills_dupes": result.get("skills_dupes", []),
        "profile": artifacts.enrichment.profile,
        "warnings": result.get("warnings", []) + artifacts.warnings + artifacts.pipeline_warnings,
        "profile_cluster": artifacts.profile_cluster,
        "pipeline_used": "canonical_compass",
        "pipeline_variant": artifacts.pipeline_variant,
        "compass_e_enabled": artifacts.compass_e_enabled,
        "domain_skills_active": artifacts.domain_skills_active,
        "domain_skills_pending_count": artifacts.domain_skills_pending_count,
        "llm_fired": artifacts.llm_fired,
        "mapping_inputs_count": len(artifacts.canonical_mapping.mapping_inputs or []),
        "structured_signal_units": artifacts.structured_extraction.structured_units,
        "top_signal_units": artifacts.structured_extraction.top_signal_units,
        "secondary_signal_units": artifacts.structured_extraction.secondary_signal_units,
        "structured_signal_stats": artifacts.structured_extraction.stats,
        "generic_filter_removed": artifacts.structured_extraction.generic_filter_removed,
        "enriched_signals": artifacts.enriched_signals.enriched_signals,
        "concept_signals": artifacts.concept_signals.concept_signals,
        "preserved_explicit_skills": artifacts.canonical_mapping.preserved_explicit_skills,
        "profile_summary_skills": artifacts.canonical_mapping.profile_summary_skills,
        "dropped_by_priority": artifacts.canonical_mapping.dropped_by_priority,
        "priority_trace": artifacts.canonical_mapping.priority_trace,
        "priority_stats": artifacts.canonical_mapping.priority_stats,
        "profile_intelligence": artifacts.profile_intelligence.data,
        "profile_intelligence_ai_assist": artifacts.profile_intelligence_ai_assist.data,
    }
